image: docker

stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  environment:
    name: dev
  tags:
    - bm-dev-kris
  before_script:
    - if [ "$CI_COMMIT_BRANCH" ==  "main" ]; then VERSION=$CI_COMMIT_BRANCH; else VERSION=$CI_COMMIT_TAG; fi;
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  only:
    refs:
      - tags
      - main
  script:
    - /kaniko/warmer --verbosity=info --image=alpine:3.20 --image=golang:alpine3.20
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination ${CI_REGISTRY_IMAGE}:$VERSION
      --destination ${CI_REGISTRY_IMAGE}:$VERSION-local
      --cache=true
      --cache-dir=/cache
      --cache-ttl=720h
      --cleanup
  when: manual

deploy_dev:
  stage: deploy
  environment:
    name: dev
  tags:
    - bm-dev-kris
  variables:
    VERSION: $CI_PIPELINE_IID
  only:
    refs:
      - main
  before_script:
    - if [ "$CI_COMMIT_BRANCH" ==  "main" ]; then VERSION=$CI_COMMIT_BRANCH; else VERSION=$CI_COMMIT_TAG; fi;
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - touch .env
    - touch .env.local
    - echo "$ENV" >> .env
    - echo "$ENV_LOCAL" >> .env.local
    - docker compose -f docker-compose.yml up -d
    - docker compose -f docker-compose-local.yml up -d
  when: manual
  needs:
    - build

deploy_prod:
  stage: deploy
  environment:
    name: prod
  tags:
    - scanin
  variables:
    VERSION: $CI_PIPELINE_IID
  only:
    refs:
      - main
  before_script:
    - if [ "$CI_COMMIT_BRANCH" ==  "main" ]; then VERSION=$CI_COMMIT_BRANCH; else VERSION=$CI_COMMIT_TAG; fi;
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - touch .env
    - echo "$ENV" >> .env
    - docker compose -f docker-compose.yml up -d
  after_script:
    - less .env 
  when: manual
  # needs:
  #   - build
