image: docker

variables:
  SERVICE_NAME: xcheck

stages:
  - deploy_dev
  - deploy_prod

deploy_dev:
  stage: deploy_dev
  environment:
    name: dev
  tags:
    - bm-dev-kris
  variables:
    VERSION: $CI_PIPELINE_IID
  script:
    - touch .env
    - echo "$ENV" >> .env
    - docker compose up -d --build

cleanup_dev:
  stage: cleanup_dev
  environment:
    name: dev
  tags:
    - bm-dev-kris
  script:
    - docker rmi $(docker images -f "dangling=true" -q --no-trunc)

deploy_prod:
  stage: deploy_prod
  environment:
    name: prod
  tags:
    - xx
  variables:
    VERSION: $CI_PIPELINE_IID
  only:
    refs:
      - main
      - tags
  script:
    - touch .env
    - echo "$ENV" >> .env
    - docker compose up -d --build
  when: manual