version: '3'
services:
    app-local:
        image: ${CI_REGISTRY_IMAGE}:$VERSION-local
        pull_policy: always
        container_name: xcheck-backend-local
        restart: unless-stopped
        tty: true
        ports:
            - '9100:9052'
        working_dir: /app
        networks:
            - external-network

    redis-db-local:
        image: redis:latest
        restart: always
        ports:
          - "36379:6379"
        networks:
            - external-network

#Docker Networks
networks:
    external-network:
        external: true
        name: external-network
