version: '3'
services:
    app:
        image: registry.bigmind.id/bigmind1/xcheck/xcheck-backend:main
        container_name: xcheck-backend
        restart: unless-stopped
        tty: true
        ports:
            - '9099:9052'
        working_dir: /app
        networks:
            - external-network

    redis-db:
        image: redis:latest
        restart: always
        ports:
          - "26379:6379"
        networks:
            - external-network

#Docker Networks
networks:
    external-network:
        external: true
        name: external-network
