version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: xcheck
        container_name: xcheck_be_service
        restart: unless-stopped
        tty: true
        ports:
            - '9099:9052'
        working_dir: /app
        networks:
            - external-network
        volumes:
            - ./config/.env.docker:/app/config/.env

    redis-db:
        image: redis:latest
        restart: always
        ports:
          - "26379:6379"
        networks:
            - external-network          

#Docker Networks
networks:
    external-network:
        external: true
        name: external-network
